# Generated by Django 4.1.3 on 2022-11-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_emprendimiento', models.CharField(max_length=200, verbose_name='Nombre del Emprendimiento')),
                ('nombre_emprendimiento', models.CharField(max_length=200, verbose_name='Nombre del Emprendimiento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('descripcion', models.TextField()),
                ('horario_apertura', models.DateTimeField()),
                ('horario_cierre', models.DateTimeField()),
                ('altitud', models.CharField(max_length=20, verbose_name='Altitud')),
                ('latitud', models.CharField(max_length=20, verbose_name='Latitud')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_local', verbose_name='Logo')),
                ('video', models.URLField(blank=True, null=True, verbose_name='video promocional')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('num_documento', models.CharField(max_length=13, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pais_origen', models.CharField(max_length=200, verbose_name='País de origen')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion_producto', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del Producto')),
                ('precio', models.IntegerField(blank=True, verbose_name='Precio del Producto')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Adminstrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.persona')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('projects.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.persona')),
            ],
            bases=('projects.persona',),
        ),
        migrations.CreateModel(
            name='Video_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True, verbose_name='video promocional')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_local', verbose_name='Logo')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento')),
            ],
            options={
                'verbose_name': 'Video e Imagenes',
                'verbose_name_plural': 'Videos e Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True, verbose_name='Puntaje')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.producto')),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
            bases=('projects.producto',),
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.persona')),
                ('emprendimientos', models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento')),
            ],
            options={
                'verbose_name': 'Personas que emprenden',
                'verbose_name_plural': 'Emprendedores(personas)',
            },
            bases=('projects.persona',),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.producto')),
                ('fecha_compra', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cliente')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
            bases=('projects.producto',),
        ),
    ]
