# Generated by Django 4.1.3 on 2022-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_categoria_alter_emprendimiento_tipo_emprendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, choices=[('hospedaje', 'Hospedaje'), ('gastronomia', 'Gastronomia'), ('turismo', 'Spot Turistico'), ('productor', 'Productor - Vendedor')], max_length=100, null=True, verbose_name='Nombre de la Categoría'),
        ),
    ]
