# Generated by Django 4.1.3 on 2022-12-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva2',
            name='nombre_producto',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.AddField(
            model_name='reserva2',
            name='nombre_producto',
            field=models.ManyToManyField(blank=True, null=True, to='projects.producto'),
        ),
    ]
