# Generated by Django 4.1.3 on 2022-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_reserva2_nombre_producto_delete_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='emprendimiento',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='producto',
            field=models.ManyToManyField(blank=True, null=True, to='projects.producto'),
        ),
    ]
