# Generated by Django 4.1.3 on 2022-12-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_producto_emprendimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='producto',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.producto'),
        ),
    ]
