# Generated by Django 4.1.3 on 2022-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_emprendimiento_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='producto',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='producto',
            field=models.ManyToManyField(blank=True, null=True, to='projects.producto'),
        ),
    ]
