# Generated by Django 4.1.3 on 2022-11-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_emprendimiento_facebook_emprendimiento_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_imagen',
            name='video',
        ),
    ]
