# Generated by Django 4.1.3 on 2022-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_video_imagen_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_imagen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Logo'),
        ),
    ]
