# Generated by Django 4.1.3 on 2022-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_video_imagen_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_imagen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/fotosSlider', verbose_name='Logo'),
        ),
    ]
