# Generated by Django 4.1.3 on 2022-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_reserva2_cedula_reserva2_correo_reserva2_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='emprendimientos',
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='emprendimientos',
            field=models.ManyToManyField(blank=True, null=True, to='projects.emprendimiento'),
        ),
    ]
