# Generated by Django 4.1.3 on 2022-12-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_emprendedor_emprendimientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, choices=[('Hospedaje y Hosterias', 'Hospedaje y Hosterias'), ('Gastronomia', 'Gastronomia'), ('Servicios', 'Servicios'), ('Productos ', 'Productos')], max_length=100, null=True, verbose_name='Nombre de la Categoría'),
        ),
        migrations.RemoveField(
            model_name='emprendimiento',
            name='tipo_emprendimiento',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='tipo_emprendimiento',
            field=models.ManyToManyField(to='projects.categoria'),
        ),
    ]
