# Generated by Django 4.1.3 on 2022-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_video_imagen_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_imagen',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
