# Generated by Django 4.1.3 on 2022-11-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_video_imagen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_imagen',
            name='iid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video_imagen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
