# Generated by Django 4.1.3 on 2022-11-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_categoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, choices=[('Hospedaje', 'Hospedaje'), ('Gastronomia', 'Gastronomia'), ('Hosterias', 'Spot Turistico'), ('Vendedores', 'Productor - Vendedor')], max_length=100, null=True, verbose_name='Nombre de la Categoría'),
        ),
    ]
