# Generated by Django 4.1.3 on 2022-11-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_emprendedor_emprendimientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='emprendimientos',
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='emprendimientos',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento'),
        ),
    ]
