# Generated by Django 4.1.3 on 2022-11-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_emprendedor_emprendimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/fotosReserva', verbose_name='Logo'),
        ),
    ]
