# Generated by Django 4.1.3 on 2022-11-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_reserva_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='emprendimiento',
        ),
        migrations.AddField(
            model_name='producto',
            name='emprendimiento',
            field=models.ManyToManyField(blank=True, related_name='productos', to='projects.emprendimiento'),
        ),
    ]
