# Generated by Django 4.1.3 on 2022-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_producto_emprendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='producto',
            field=models.ManyToManyField(blank=True, to='projects.producto'),
        ),
    ]
