# Generated by Django 4.1.3 on 2022-12-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, choices=[('Hospedaje y Hosterias', 'Hospedaje y Hosterias'), ('Gastronomia', 'Gastronomia'), ('Servicios y Spots Turisticos', 'Servicios y Spots Turisticos'), ('Productos ', 'Productos')], max_length=100, null=True, verbose_name='Nombre de la Categoría'),
        ),
    ]
