# Generated by Django 4.1.3 on 2022-12-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_productos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Productos'),
        ),
    ]
