# Generated by Django 4.1.3 on 2022-12-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_reserva_cantidad_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_productos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_vencimiento',
        ),
    ]
