# Generated by Django 4.1.3 on 2022-12-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_rename_fecha_reserva_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='foto',
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/fotosReserva', verbose_name='Logo'),
        ),
    ]
