# Generated by Django 4.1.3 on 2022-12-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_reserva_foto_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
    ]
