# Generated by Django 4.1.3 on 2022-12-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_remove_producto_cantidad_reserva2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva2',
            options={'verbose_name': 'Reserva2', 'verbose_name_plural': 'Reservas2'},
        ),
        migrations.RenameField(
            model_name='reserva2',
            old_name='producto',
            new_name='nombre_producto',
        ),
    ]
