# Generated by Django 4.1.3 on 2022-12-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_reserva2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendimiento',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='emprendimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.emprendimiento'),
        ),
    ]
