# Generated by Django 4.1.3 on 2022-12-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_remove_emprendimiento_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='emprendimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='projects.emprendimiento'),
        ),
    ]
